### PR TITLE
Run CI checks on pull requests to main

### LINKED ISSUE #273: Run CI on pushes to PRs
Right now, CI is only setup to run on post merge. This is because the project was in limited development and I was the sole contributor for awhile. We should require CI to run for PRs before merging _as well as_ post merge.

### PR DESCRIPTION
**Pull request by uncenter**
Closes #273. Check failure is fixed by #272.

### CODE REVIEW

**Comment by nickgerace** [comment]
@uncenter you likely need to rebase and force push

**Comment by nickgerace** [comment]
By the way @uncenter, random thought while I'm here, you should join the SI Discord or at least check out the [repo](https://github.com/systeminit/si). Lot of Rust code to play around with there.

**Comment by uncenter** [comment]
> @uncenter you likely need to rebase and force push

Are there conflicts? GitHub isn't alerting me of any afaik.

**Comment by nickgerace** [comment]
@uncenter none, but you likely need to rebase to get the newest `.github` workflows

**Comment by uncenter** [comment]
To get the checks to pass here you mean? I don't think we need to wait for that since if it passes on main it passes here (the check failure only serves to show it is working and running on pull requests!). I can rebase anyway though.

**Comment by uncenter** [comment]
> By the way @uncenter, random thought while I'm here, you should join the SI Discord or at least check out the [repo](https://github.com/systeminit/si). Lot of Rust code to play around with there and it's where I spend the vast majority of my programming time at present.

Joined the Discord, thanks!

**Pull request merged**
